/* The demo script, in one place. The prompter and the printable page both read this file.
   A block plays as up to three phases: DO (press these keys), SPEAK (read this line), HOLD
   (stay silent while something happens on screen). `cue` is the tail the prompter listens
   for, so it moves when you finish rather than when a timer says so.

   Three OBS scenes, one window each: F1 the television, F2 the family page, F3 Alexa. */
window.VITA_SCRIPT = {
  title: 'Vita Heart \u00b7 demo',
  target: 170,
  actSeconds: 1.8,
  scenes: {F1: 'TV', F2: 'FAMILY', F3: 'ALEXA'},
  blocks: [
    { t: 0, scene: 'TV', hold: 0, actFirst: false,
      say: 'This is Vita Heart on Vega OS: the television an older parent already watches, turned into their health room. Ahmet is seventy-two and lives alone. Everything here is live.',
      cue: 'everything here is live',
      do: [],
      recover: '' },
    { t: 12, scene: 'TV', hold: 0, actFirst: false,
      say: 'İyi akşamlar means good evening. The television greets him in his own language, one of twenty-three. One tablet due, one line from his daughter, one button.',
      cue: 'one button',
      drive: 'checkin', do: ['The television answers for him'],
      recover: '' },
    { t: 25, scene: 'FAMILY', hold: 2, actFirst: true,
      say: 'His daughter\'s page knows in under a second. Every screen here reads the same events channel.',
      cue: 'the same events channel',
      do: ['Press F2 · family page'],
      recover: 'If the tick is slow, keep talking. Never press again.' },
    { t: 36, scene: 'TV', hold: 0, actFirst: true,
      say: 'These boxes were photographed once, from Selin\'s phone. Nova Lite read the print, RxNorm confirmed it, openFDA found live recalls against specific batches.',
      cue: 'against specific batches',
      drive: 'meds', do: ['Press F1 · television'],
      recover: '' },
    { t: 47, scene: 'TV', hold: 0, actFirst: false,
      say: 'The television never says recalled. It gives him the question to ask the pharmacist.',
      cue: 'ask the pharmacist',
      drive: 'confirm', do: ['The tablet is confirmed'],
      recover: 'If no dose is due, say: the dose window is later today, here is this morning’s list.' },
    { t: 55, scene: 'ALEXA', hold: 3, actFirst: true,
      say: 'How is Dad doing today?',
      cue: 'how is dad doing today',
      drive: 'listen', do: ['Press F3 · Alexa page', 'the microphone opens itself'],
      recover: 'If the microphone misses, type the sentence and press Enter. Say nothing about it.' },
    { t: 62, scene: 'ALEXA', hold: 3, actFirst: true,
      say: 'Tell Vita Heart he took the evening Glifor already.',
      cue: 'evening glifor already',
      drive: 'listen', do: ['the microphone opens again'],
      recover: '' },
    { t: 71, scene: 'TV', hold: 0, actFirst: true,
      say: 'Voice, the remote and the screen in one flow. Behind it, a real MCP server on the 2025 spec; the Alexa+ toolkit is partner-only, so this is the sanctioned simulation.',
      cue: 'the sanctioned simulation',
      do: ['Press F1 · television'],
      recover: '' },
    { t: 85, scene: 'TV', hold: 1, actFirst: false,
      say: 'Ten minutes, seated.',
      cue: 'ten minutes seated',
      drive: 'session', do: ['The session starts'],
      recover: '' },
    { t: 90, scene: 'TV', hold: 3, actFirst: false,
      say: 'That is his real heart rate, from his own Watch, on his own television.',
      sayRecorded: 'This is a recorded session, and the television says so under the number. With the Watch on his wrist, that number is live.',
      cue: 'on his own television',
      do: ['Watch the number arrive'],
      recover: 'If no number in 15 s: say the Watch is out of range, here is a recorded session, labelled as such.' },
    { t: 101, scene: 'TV', hold: 2, actFirst: false,
      say: 'The coach adapts: twenty seconds above the ceiling ends the set early. When a recording is used instead of a wrist, the screen says so.',
      cue: 'the screen says so',
      drive: 'stop', do: ['The session is saved'],
      recover: '' },
    { t: 115, scene: 'TV', hold: 0, actFirst: true,
      say: 'Every tool call the agents made is on his own screen. Nothing is said about him behind his back.',
      cue: 'behind his back',
      drive: 'family', do: ['The television opens Family'],
      recover: '' },
    { t: 125, scene: 'FAMILY', hold: 0, actFirst: true,
      say: 'The front door and the hall are Ring sensors, signed exactly as Ring signs them. Simulated: there is no Ring device in this flat.',
      cue: 'no ring device in this flat',
      do: ['Press F2 · family page'],
      recover: '' },
    { t: 137, scene: 'FAMILY', hold: 0, actFirst: false,
      say: 'This is what Selin reads at nine. At three ten the door opened, the hall has been under eighteen degrees since six, he took both tablets and did his session. Strands agents wrote it from facts only.',
      cue: 'wrote it from facts only',
      do: [],
      recover: 'Read what the page actually says. Never read a sentence that is not on it.' },
    { t: 152, scene: 'TV', hold: 0, actFirst: true,
      say: 'Why the television: adults over sixty-five watch more than anyone, and their children live elsewhere. Vita Heart is native on Vega OS, and it joins the living room, the front door and the cloud on AWS. Thank you.',
      cue: 'thank you',
      do: ['Press F1 · television'],
      recover: '' },
  ],
};
