/* The demo script, in one place. The prompter and the printable page both read this file.
   A block plays as up to four phases: DO (press these keys), SPEAK (read this line), HOLD
   (stay silent while something happens on screen), then the next block. `cue` is the tail
   the prompter listens for so it moves when you finish, not when a timer says so. */
window.VITA_SCRIPT = {
  title: 'Vita Heart \u00b7 demo',
  target: 166,
  actSeconds: 1.8,
  scenes: {F1: 'TV', F2: 'FAMILY', F3: 'ALEXA', F4: 'TERMINAL', F5: 'WRIST'},
  blocks: [
    { t: 0, scene: 'TV', hold: 0, actFirst: false,
      say: 'This is Vita Heart on Vega OS: the television an older parent already watches, turned into their health room. Ahmet is seventy-two and lives alone. Everything here is live.',
      cue: 'everything here is live',
      do: [],
      recover: '' },
    { t: 12, scene: 'TV', hold: 0, actFirst: false,
      say: 'The television greets him in his own language. One tablet due, one line from his daughter, one button.',
      cue: 'one button',
      do: ['Press OK on I\'m up'],
      recover: 'If the button is not focused, press ↓ then OK.' },
    { t: 19, scene: 'FAMILY', hold: 2, actFirst: true,
      say: 'His daughter\'s page knows in under a second. Every screen here reads the same events channel.',
      cue: 'the same events channel',
      do: ['Press F2 · family window'],
      recover: 'If the tick is slow, keep talking. Never press again.' },
    { t: 30, scene: 'TV', hold: 0, actFirst: true,
      say: 'These boxes were photographed once, from Selin\'s phone. Nova Lite read the print, RxNorm confirmed it, openFDA found live recalls against specific batches.',
      cue: 'against specific batches',
      do: ['Press F1 · TV', '↓ to Show me, then OK'],
      recover: '' },
    { t: 41, scene: 'TV', hold: 0, actFirst: false,
      say: 'The television never says recalled. It gives him the question to ask the pharmacist.',
      cue: 'ask the pharmacist',
      do: ['Press OK on I took it'],
      recover: 'If no dose is due, say: the dose window is later today, here is this morning’s list.' },
    { t: 49, scene: 'ALEXA', hold: 3, actFirst: true,
      say: 'How is Dad doing today?',
      cue: 'how is dad doing today',
      do: ['Press F3 · Alexa window', 'Click the microphone'],
      recover: 'If the microphone misses, type the sentence and press Enter. Say nothing about it.' },
    { t: 57, scene: 'ALEXA', hold: 3, actFirst: true,
      say: 'Tell Vita Heart he took the evening Glifor already.',
      cue: 'evening glifor already',
      do: ['Click the microphone again'],
      recover: '' },
    { t: 66, scene: 'TV', hold: 0, actFirst: true,
      say: 'Voice, the remote and the screen in one flow. Behind it, a real MCP server on the 2025 spec; the Alexa+ toolkit is partner-only, so this is the sanctioned simulation.',
      cue: 'the sanctioned simulation',
      do: ['Press F1 · TV'],
      recover: '' },
    { t: 80, scene: 'TV', hold: 1, actFirst: false,
      say: 'Ten minutes, seated.',
      cue: 'ten minutes seated',
      do: ['→ Ten minutes, seated', 'OK', 'Press Start on the Watch'],
      recover: '' },
    { t: 84, scene: 'WRIST', hold: 3, actFirst: true,
      say: 'That is his real heart rate, from his own Watch, on his own television.',
      cue: 'on his own television',
      do: ['Press F5 · webcam', 'Hold your wrist up'],
      recover: 'No webcam scene? Stay on F1 and say the same words. The number on the television is the proof.' },
    { t: 95, scene: 'TV', hold: 2, actFirst: true,
      say: 'The coach adapts: twenty seconds above the ceiling ends the set early. When a recording is used instead of a wrist, the screen says so.',
      cue: 'the screen says so',
      do: ['Press F1 · TV'],
      recover: '' },
    { t: 110, scene: 'TERMINAL', hold: 2, actFirst: true,
      say: 'Ring sensors at the door and in the hall, signed exactly as Ring signs them. Simulated: there is no Ring device in this flat.',
      cue: 'no ring device in this flat',
      do: ['Press F4 · terminal', 'Press Return on the ring command'],
      recover: '' },
    { t: 123, scene: 'TV', hold: 0, actFirst: true,
      say: 'Every tool call the agents made is on his own screen. Nothing is said about him behind his back.',
      cue: 'behind his back',
      do: ['Press F1 · TV', '↓ to Family, then OK'],
      recover: '' },
    { t: 133, scene: 'FAMILY', hold: 0, actFirst: true,
      say: 'Selin, at three ten the front door opened, the hall has been under eighteen degrees since six, he took both tablets and did his session. Strands agents wrote that from facts only.',
      cue: 'wrote that from facts only',
      do: ['Press F2 · family window'],
      recover: 'Read what the page actually says. Never read a sentence that is not on it.' },
    { t: 148, scene: 'TV', hold: 0, actFirst: true,
      say: 'Why the television: adults over sixty-five watch more than anyone, and their children live elsewhere. Vita Heart is native on Vega OS, and it joins the living room, the front door and the cloud on AWS. Thank you.',
      cue: 'thank you',
      do: ['Press F1 · TV'],
      recover: '' },
  ],
};
