/* The demo script, in one place. The prompter and the printable page both read this file.
   A block plays as up to three phases: DO (something happens), SPEAK (read this line),
   HOLD (stay silent while the screen catches up). `cue` is the tail the prompter listens
   for, so it moves when you finish rather than when a timer says so.

   The camera is not your job: obs_director.py switches scenes on `scene` below.

   Length is a rule, not a preference: "Demo video under 3 minutes… judges aren't required
   to watch past the 3-minute mark." A first take ran 3:52 — 312 words plus four and a half
   seconds of grace after every line. This is 237 words and the grace is 1.2 s. */
window.VITA_SCRIPT = {
  title: 'Vita Heart · demo',
  target: 150,
  actSeconds: 1.0,
  scenes: {F1: 'TV', F2: 'FAMILY', F3: 'ALEXA'},
  blocks: [
    { t: 0, scene: 'TV', hold: 0, actFirst: false,
      say: 'Vita Heart, native on Vega OS: the television an older parent already watches, turned into a health room. Ahmet is seventy-two, alone.',
      cue: 'seventy-two alone',
      do: [],
      recover: '' },
    { t: 11, scene: 'TV', hold: 0, actFirst: false,
      say: 'It greets him in Turkish, one of twenty-three languages. One tablet due, one line from his daughter, one button.',
      cue: 'one button',
      drive: 'checkin', do: ['The television answers for him'],
      recover: '' },
    { t: 21, scene: 'FAMILY', hold: 1, actFirst: true,
      say: 'His daughter\'s page knows in under a second. Every screen reads the same events channel.',
      cue: 'same events channel',
      do: ['The family page updates itself'],
      recover: 'If the tick is slow, keep talking. Never press anything.' },
    { t: 30, scene: 'TV', hold: 0, actFirst: true,
      say: 'Photographed once from Selin\'s phone. Nova Lite read the print, RxNorm confirmed it, openFDA found live recalls against specific batches.',
      cue: 'against specific batches',
      drive: 'meds', do: ['The medicines open'],
      recover: '' },
    { t: 42, scene: 'TV', hold: 0, actFirst: false,
      say: 'The television never says recalled. It gives him the question to ask the pharmacist.',
      cue: 'ask the pharmacist',
      drive: 'confirm', do: ['The tablet is confirmed'],
      recover: 'If no dose is due, say: the dose window is later today, here is this morning’s list.' },
    // actFirst is false on both Alexa blocks on purpose: the sentence is spoken first and
    // the surface is asked afterwards. Driving it first had Alexa talking over the line.
    { t: 50, scene: 'ALEXA', hold: 12, actFirst: false,
      say: 'How is Dad doing today?',
      cue: 'how is dad doing today',
      drive: 'listen', ask: 'How is Dad doing today?', do: ['Alexa answers — say nothing over it'],
      recover: 'If nothing appears, type the sentence and press Enter. Say nothing about it.' },
    { t: 60, scene: 'ALEXA', hold: 12, actFirst: false,
      say: 'Tell Vita Heart he took the evening Glifor already.',
      cue: 'evening glifor already',
      drive: 'listen', ask: 'Tell Vita Heart he took the evening Glifor already.',
      do: ['Alexa answers — say nothing over it'], recover: '' },
    { t: 72, scene: 'TV', hold: 0, actFirst: true,
      say: 'One flow, over a real MCP server on the 2025 spec. The Alexa+ toolkit is partner-only, so this page stands in for it.',
      cue: 'stands in for it',
      do: ['Back on the television'],
      recover: '' },
    { t: 83, scene: 'TV', hold: 1, actFirst: false,
      say: 'Ten minutes, seated.',
      cue: 'ten minutes seated',
      drive: 'session', do: ['The session starts'],
      recover: '' },
    { t: 87, scene: 'TV', hold: 2, actFirst: false,
      say: 'That is his real heart rate, from his own Watch, on his own television.',
      sayRecorded: 'This is a recorded session, and the television says so under the number. With the Watch on his wrist, that number is live.',
      cue: 'on his own television',
      do: ['The number arrives'],
      recover: 'If no number in 15 s: say the Watch is out of range, here is a recorded session, labelled as such.' },
    { t: 95, scene: 'TV', hold: 1, actFirst: false,
      say: 'The coach adapts: twenty seconds over the ceiling ends the set early. A recording instead of a wrist is labelled on screen.',
      cue: 'labelled on screen',
      drive: 'stop', do: ['The session is saved'],
      recover: '' },
    { t: 106, scene: 'TV', hold: 0, actFirst: true,
      say: 'Every tool call is on his own screen. Nothing is said behind his back.',
      cue: 'behind his back',
      drive: 'family', do: ['The television opens Family'],
      recover: '' },
    { t: 113, scene: 'FAMILY', hold: 0, actFirst: true,
      say: 'Front door and hall are Ring sensors, signed as Ring signs them. Simulated: no Ring device here.',
      cue: 'no ring device here',
      do: ['The family page'],
      recover: '' },
    { t: 123, scene: 'FAMILY', hold: 0, actFirst: false,
      say: 'This is what Selin reads at nine: the door at three ten, the hall cold since six, the dose, the session. Strands agents, facts only.',
      cue: 'facts only',
      do: [],
      recover: 'Read what the page actually says. Never read a sentence that is not on it.' },
    { t: 135, scene: 'TV', hold: 0, actFirst: true,
      say: 'Over-sixty-fives watch more television than anyone, and their children live elsewhere. Vita Heart joins all of it, on AWS. Thank you.',
      cue: 'thank you',
      do: ['Back on the television'],
      recover: '' },
  ],
};
